# syntax=docker/dockerfile:1
FROM python:3.12-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

# Set work directory
WORKDIR /app

# Install Google Chrome
RUN apt-get update \
    && apt-get install -y wget gnupg2 \
    && wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update \
    && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

# Install the application dependencies.
RUN uv sync --frozen --no-cache

# Expose port
EXPOSE 8000

# Run the application.
#CMD ["uv", "run", "ahorratron-api"]
CMD ["uv", "run", "uvicorn", "ahorratron.sync_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
